project_name: pinger
release:
  github:
    owner: pasdoy
    name: pinger
  name_template: '{{.Tag}}'
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: pinger
  hooks:
    pre: make build
    post: packr clean
  env:
    - CGO_ENABLED=0
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'